server:
  port: 2004

#服务名称#
spring:
  application:
    name: zuul-server
  profiles:
    active: dev

#服务中心默认地址#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

#配置zuul网关#
zuul:
  routes:
    order-api:
      path: /order-api/**
      serviceId: order-service
    user-api:
      path: /user-api/**
      serviceId: user-service
    comment-api:
      path: /comment-api/**
      serviceId: comment-service

#ribbon:
#  eureka:
#    enabled: false
#
#order-api:
#  ribbon:
#    listOfServers: localhost,localhost