
spring:
  profiles:
    active: dev
  datasource:
    url: 'jdbc:mysql://10.40.254.59:4000/xgqoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: 2018
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小连接数#
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000
  redis:
    host: 10.40.254.59
    port: 6379
    password:
    pool:
      max-active: 10
      max-idle: 5
      max-wait: -1
      min-idle: 0
    timeout: 0
  #消息总线相关配置
  rabbitmq:
    host: 10.40.253.210
    port: 5672
    username: admin
    password: 123456
#  zipkin:
#    base-url: http://10.40.254.210:9411
  #链路追踪采样率，默认0.1 即10次请求只记录一次
  sleuth:
    sampler:
      percentage: 1.0
#  配置中心
  cloud:
    config:
      uri: http://10.40.253.210:2005/
      label: master
      profile: dev

#Eureke 客户端注册服务相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.253.210:2000/eureka

#logback相关配置
logging:
  level:
    com.icecreamGroup.order.Mapper: debug
    org.springframwork.cloud.sleuth: debug


#关闭security相关验证
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

tm:
  manager.url: http://10.40.255.238:8899/tx/manager/
server:
  port: 2001
