server:
  port: 2001
spring:
  profiles:
    active: home
  datasource:
    url: 'jdbc:mysql://localhost:3306/xgqoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: root
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小连接数#
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000
      initial-size: 2
      test-on-borrow: false
      test-while-idle: true
      pool-prepared-statements: false
  #消息总线相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  #链路追踪采样率，默认0.1 即10次请求只记录一次
  sleuth:
    sampler:
      percentage: 1.0
#Eureke 客户端注册服务相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka

#logback相关配置
logging:
  level:
    com.codingapi: debug
    com.icecreamGroup.order.Mapper: debug


#关闭security相关验证
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

tm:
  manager.url: http://localhost:8899/tx/manager/
