server:
  port: 2002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: user-service
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: 'jdbc:mysql://10.40.254.59:4000/xgq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: 2018
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小连接数
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

#开启feign客户端路由
feign:
  hystrix:
    enabled: true

#日志处理/链路日志处理
logging:
  level:
    root: info
    com.codingapi: debug
    com.icecreamGroup.user.Mapper: debug
    com.icecreamGroup.user.feignClients.OrderFeignClient: debug


#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

tm:
  manager.url: http://10.40.255.238:8899/tx/manager/
